---
- name: Enable amdfan service
  become: true
  ansible.builtin.service:
    name: amdfan
    state: restarted

- name: Enable amdgpu-clocks service
  become: true
  ansible.builtin.service:
    name: amdgpu-clocks
    state: restarted
