---
- name: Create all dotfiles related folders
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: "../templates"
  when: item.state == 'directory'

- name: Copy all dotfiles
  ansible.builtin.template:
    src: "{{ item.path }}"
    dest: "{{ xdg_config_home }}/{{ item.path | replace('.j2', '') }}"
    mode: "0644"
  with_community.general.filetree: "../templates"
  when:
    - item.state == 'file'
