---
- name: Install all sensor packages
  kewlfft.aur.aur:
    name:
      - linux-headers
      - lm_sensors
      - zenpower3-dkms
  notify: Detect sensors

- name: Allow all handlers to run
  ansible.builtin.meta: flush_handlers
