---
### Environment variables

xdg_config_home: $HOME/.config
xdg_cache_home: $HOME/.cache
xdg_data_home: $HOME/.local/share
xdg_state_home: $HOME/.local/state
xdg_bin_home: $HOME/.local/bin

### Pacman

pacman:
  parallel_downloads: 10
  countries:
    - France
  aur_helper: yay

### Fish

fish:
  modules:
    - jorgebucaran/autopair.fish
    - jhillyerd/plugin-git

### GPU Overclocking

gpu_overclocking:
  systemd_boot_loader_file: arch.conf
  max_gpu_clock: 2500MHz # default value: 2334Mhz, max 2600MHz
  max_vram_clock: 1000MHz # default value: 1000Mhz, max 1075MHz
  voltage_offset: -75mV # default value: 0mV
  max_gpu_power: 200000000 # in micro watts default value: 203000000
  fan_speed_matrix:
    - [4, 25]
    - [60, 25]
    - [80, 40]
    - [95, 100]

### Apps

apps:
  - ark # Archive manager
  - dolphin # File manager
  - kcalc # calculator
  - spectacle # Screenshot utility
  - gwenview # image viewer
  - firefox # browser
  - vlc # Video and music player
  - btop # TUI system monitor
  - visual-studio-code-bin # Visual text editor
  - neovim # Neovim text editor
  - less # pager
  - discord # Discord client
  - xwaylandvideobridge # Allow desktop sharing on Discord using Wayland
  - signal-desktop # Signal client
  - hunspell # System wide spell checker
  - hunspell-en_gb # English support
  - hunspell-fr # French support

### Automatic turn off:

automatic_turn_off:
  times:
    - Mon..Thu,Sun *-*-* 23:00:00
    - Sat,Sun *-*-* 02:00:00
